#! /bin/sh

# Autostart Apps
pgrep -x sxhkd > /dev/null || sxhkd &

picom &

# Polybar
~/.config/polybar/launch.sh &

# Wallpaper
feh --bg-fill ~/Images/wallpaper.png &

# Workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config focus_follows_pointer false

#bspc config top_padding           20

# Borders
bspc config focused_border_color "#61AFEF"
bspc config normal_border_color  "#282c34"
bspc config border_width         2
bspc config borderless_monocle   true

# Gaps
bspc config window_gap           12
bspc config split_ratio          0.50
bspc config gapless_monocle      true

# Rules
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
bspc rule -a Google-chrome desktop='^1' follow=on
bspc rule -a firefox desktop='^2' follow=on
bspc rule -a spotify desktop='^0' follow=on

# For more check WM_CLASS with command xprop

# USB storage devices
udiskie &